# Use the official Node.js image as the base image
# 도커 허브에서 확인하여 가장 적합한 버전을 선택할 것
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port the app runs on
EXPOSE 5173

# Start the application
CMD ["npm", "run", "dev"]

# Build the Docker image
# docker build -t react-app-dev -f Dockerfile.dev .

# vite.config.js 파일을 수정하여 호스트를
# 수정
# export default defineConfig({
#   server: {
#     host: '0.0.0.0',  // 모든 네트워크 인터페이스에서 접근 가능하도록 설정
#     port: 5173, // 포트 번호를 5173으로 설정
#     strictPort: true, // 포트 충돌이 발생하면 에러를 발생시키도록 설정
#   },
#   ...
# });

# Run the Docker container
# docker run -it -p 5173:5173 --name react-app react-app